on: [push]
name: build
jobs:
  check:
    name: Check project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    - uses: actions-rs/cargo@v1
      with:
        command: check
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
