on: [push]
name: build
jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
    - name: Install minimal stable with clippy and rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
